#!/usr/bin/env bash
# =============================================================================
# provision_azure.sh — Provision Azure infrastructure for the Salesforce AI Assistant
# Wraps az deployment sub create with the appropriate Bicep files.
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
BICEP_DIR="$REPO_ROOT/infra/bicep"

# --- Defaults ---
ENVIRONMENT="${1:-dev}"
LOCATION="${AZURE_LOCATION:-eastus2}"

# Read projectName from the Bicep params file to stay in sync
PARAMS_FILE_EARLY="$BICEP_DIR/env/${ENVIRONMENT}.bicepparam"
if [[ -z "${AZURE_PROJECT_NAME:-}" && -f "$PARAMS_FILE_EARLY" ]]; then
    AZURE_PROJECT_NAME=$(grep -E "^param projectName" "$PARAMS_FILE_EARLY" | sed "s/.*= *'\(.*\)'/\1/" || echo "")
fi
PROJECT_NAME="${AZURE_PROJECT_NAME:-sf-ai-assistant}"
DEPLOYMENT_NAME="sf-ai-assistant-${ENVIRONMENT}-$(date +%Y%m%d%H%M%S)"

# --- Validate environment ---
if [[ ! "$ENVIRONMENT" =~ ^(dev|test|prod)$ ]]; then
    echo "❌ Invalid environment: $ENVIRONMENT (must be dev, test, or prod)"
    exit 1
fi

PARAMS_FILE="$BICEP_DIR/env/${ENVIRONMENT}.bicepparam"
if [[ ! -f "$PARAMS_FILE" ]]; then
    echo "❌ Parameters file not found: $PARAMS_FILE"
    exit 1
fi

echo "=============================================="
echo "  Salesforce AI Assistant — Azure Provisioning"
echo "=============================================="
echo "  Environment:  $ENVIRONMENT"
echo "  Location:     $LOCATION"
echo "  Project:      $PROJECT_NAME"
echo "  Params file:  $PARAMS_FILE"
echo "=============================================="
echo ""

# --- Step 1: Validate the template ---
echo "🔍 Validating Bicep template..."
az deployment sub validate \
    --name "$DEPLOYMENT_NAME-validate" \
    --location "$LOCATION" \
    --template-file "$BICEP_DIR/main.bicep" \
    --parameters "$PARAMS_FILE" \
    --no-prompt \
    --output table

echo "✅ Validation passed"
echo ""

# --- Step 2: What-if (preview changes) ---
echo "📋 Previewing changes (what-if)..."
az deployment sub what-if \
    --name "$DEPLOYMENT_NAME-whatif" \
    --location "$LOCATION" \
    --template-file "$BICEP_DIR/main.bicep" \
    --parameters "$PARAMS_FILE" \
    --no-prompt

echo ""
read -rp "Proceed with deployment? [y/N] " confirm
if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
    echo "Deployment cancelled."
    exit 0
fi

# --- Step 3: Deploy ---
echo ""
echo "🚀 Deploying infrastructure..."
DEPLOYMENT_OUTPUT=$(az deployment sub create \
    --name "$DEPLOYMENT_NAME" \
    --location "$LOCATION" \
    --template-file "$BICEP_DIR/main.bicep" \
    --parameters "$PARAMS_FILE" \
    --no-prompt \
    --output json)

echo "✅ Deployment complete"
echo ""

# --- Step 4: Extract outputs → .env ---
echo "📝 Extracting outputs to .env.azure..."

AI_ENDPOINT=$(echo "$DEPLOYMENT_OUTPUT" | python3 -c "import sys,json; print(json.load(sys.stdin)['properties']['outputs']['aiFoundryProjectEndpoint']['value'])" 2>/dev/null || echo "")
OPENAI_DEPLOYMENT=$(echo "$DEPLOYMENT_OUTPUT" | python3 -c "import sys,json; print(json.load(sys.stdin)['properties']['outputs']['openaiDeploymentName']['value'])" 2>/dev/null || echo "")
KV_URI=$(echo "$DEPLOYMENT_OUTPUT" | python3 -c "import sys,json; print(json.load(sys.stdin)['properties']['outputs']['keyVaultUri']['value'])" 2>/dev/null || echo "")
STORAGE=$(echo "$DEPLOYMENT_OUTPUT" | python3 -c "import sys,json; print(json.load(sys.stdin)['properties']['outputs']['storageAccountName']['value'])" 2>/dev/null || echo "")
APPINSIGHTS=$(echo "$DEPLOYMENT_OUTPUT" | python3 -c "import sys,json; print(json.load(sys.stdin)['properties']['outputs']['appInsightsConnectionString']['value'])" 2>/dev/null || echo "")
HOSTING_MODE=$(echo "$DEPLOYMENT_OUTPUT" | python3 -c "import sys,json; print(json.load(sys.stdin)['properties']['outputs']['hostingMode']['value'])" 2>/dev/null || echo "none")
MCP_CRM_URL=$(echo "$DEPLOYMENT_OUTPUT" | python3 -c "import sys,json; print(json.load(sys.stdin)['properties']['outputs']['mcpCrmUrl']['value'])" 2>/dev/null || echo "")
MCP_KB_URL=$(echo "$DEPLOYMENT_OUTPUT" | python3 -c "import sys,json; print(json.load(sys.stdin)['properties']['outputs']['mcpKnowledgeUrl']['value'])" 2>/dev/null || echo "")
ACR_LOGIN_SERVER=$(echo "$DEPLOYMENT_OUTPUT" | python3 -c "import sys,json; print(json.load(sys.stdin)['properties']['outputs']['acrLoginServer']['value'])" 2>/dev/null || echo "")

ENV_FILE="$REPO_ROOT/.env.azure"
cat > "$ENV_FILE" <<EOF
# Auto-generated by provision_azure.sh — ${ENVIRONMENT} environment
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

AZURE_PROJECT_NAME=${PROJECT_NAME}
AZURE_AI_PROJECT_ENDPOINT=${AI_ENDPOINT}
AZURE_AI_MODEL_NAME=${OPENAI_DEPLOYMENT}
AZURE_KEY_VAULT_URI=${KV_URI}
AZURE_STORAGE_ACCOUNT_NAME=${STORAGE}
APPLICATIONINSIGHTS_CONNECTION_STRING=${APPINSIGHTS}
HOSTING_MODE=${HOSTING_MODE}
MCP_CRM_URL=${MCP_CRM_URL}
MCP_KB_URL=${MCP_KB_URL}
ACR_LOGIN_SERVER=${ACR_LOGIN_SERVER}
EOF

echo "  Written to: $ENV_FILE"
echo ""
echo "=============================================="
echo "  Provisioning complete!"
echo ""
echo "  Hosting mode: $HOSTING_MODE"
echo ""
echo "  Next steps:"
echo "  1. Copy Salesforce credentials to Key Vault:"
echo "     az keyvault secret set --vault-name <vault> --name sf-client-id --value <id>"
echo "     az keyvault secret set --vault-name <vault> --name sf-client-secret --value <secret>"
echo "  2. Merge .env.azure into .env:"
echo "     cat .env.azure >> .env"
if [[ "$HOSTING_MODE" == "aca" ]]; then
echo "  3. Build and deploy container images:"
echo "     ./scripts/deploy_app.sh $ENVIRONMENT aca"
elif [[ "$HOSTING_MODE" == "appService" ]]; then
echo "  3. Deploy application to App Service:"
echo "     ./scripts/deploy_app.sh $ENVIRONMENT appService"
else
echo "  3. Run notebooks to verify connectivity (stdio mode)."
fi
echo "=============================================="
